version: '2'
services:
  x11:
    build: ./x11
    restart: always
    environment:
      - DISPLAY=:0
    ports:
      - "6000:6000"
    volumes:
      - 'x11_data:/usr/src/app'

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  x11_data:
